# Generated by Django 4.2 on 2023-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rockets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocket_id', models.CharField(max_length=200)),
                ('rocket_name', models.CharField(max_length=200)),
                ('rocket_type', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('stages', models.IntegerField(default=0)),
                ('boosters', models.IntegerField(default=0)),
                ('cost_per_launch', models.FloatField(default=0)),
                ('ingredients', models.CharField(max_length=400)),
                ('success_rate_pct', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('wikipedia', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
    ]
